Option:
  Language: zh_CN
  UUIDMode: false
  Saving: YAML
  DateFormat: 'yyyy-MM-dd hh:mm:ss'

MySQL:
  host: localhost
  port: 3306
  database: minecraft
  username: test
  password: 123

RedeemCode:
  Length: 10
  Involved: ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz1234567890
  Gifts:
    A:
      VIPGroup: 'VIP1'
      days: 3
    B:
      VIPGroup: 'VIP2'
      days: -1

VIP:
  DefaultGroup: '#nochange'
  GroupPlaceholder: '%vault_rank%'
  Command:
    MoveGroup: 'manuadd %player% %group%'
    AddPerm: 'manuaddp %player% %perm%'
    DelPerm: 'manudelp %player% %perm%'
    OnActivate:
      - 'say 玩家%player_name%开通了尊贵用户组，可享有不同的待遇福利！'
    OnExpire:
      - 'say 玩家%player_name%的尊贵用户组已过期，拥有的福利加持已消失！'
  Group:
    VIP1:
      FriendlyName: '&6尊贵玩家1级'
      MovePermGroup: true
      PermGroup: 'vip1'
      ExtraPerm:
        - vip.fly
        - vip.tp
      Priority: 0
    VIP2:
      FriendlyName: '&6尊贵玩家2级'
      MovePermGroup: true
      PermGroup: 'vip2'
      ExtraPerm:
        - vip.fly
        - vip.tp
      Priority: 1
